import { useEffect, useRef, useState } from 'react';
import { useEditing } from '../../picker/context';
import { filterSpecs, parseShadow, readFilter, serializeShadow, splitCSS, updateFilter, hiddenShadow, originalShadow } from '../../editing/rich';
import { boxPresets, textPresets } from '../../editing/presets';
import { Section } from './Controls';
import { contextKey } from './RichControls';
import { Icon, IconButton } from '../shared/Icon';
import { NumericScrubber } from '../shared/NumericScrubber';
import { ColorControl } from '../shared/ColorControl';
import s from '../ui.module.css';
import h from './shadows.module.css';

export function RichShadow({ text = false }: { text?: boolean }) {
  const { editor, design } = useEditing(); const [selected, setSelected] = useState(0);
  const property = text ? 'text-shadow' : 'box-shadow', name = text ? 'Text' : 'Box';
  const value = design!.values[property].presented, list = value === 'none' ? [] : splitCSS(value);
  const index = Math.min(selected, Math.max(0, list.length - 1)), original = originalShadow(list[index] ?? ''), shadow = parseShadow(original ?? list[index] ?? '', text);
  const commit = (next: string[], gesture?: string) => editor!.apply(design!.targetId, property, next.join(', ') || 'none', gesture);
  const update = (patch: Partial<NonNullable<typeof shadow>>, gesture?: string) => { if (!shadow) return false; const next = serializeShadow({ ...shadow, ...patch }, text); return commit(list.map((item, i) => i === index ? original ? hiddenShadow(next) : next : item), gesture); };
  const move = (from: number, to: number) => { const next = [...list]; [next[from], next[to]] = [next[to], next[from]]; if (commit(next)) setSelected(to); };
  const presets = text ? textPresets : boxPresets;
  return <Section name={`${name} shadow`}><div className={`${s.sessionActions} ${h.actions}`}><button className={s.addButton} onClick={() => { if (commit([...list, '0px 4px 12px #0004'])) setSelected(list.length); }}><Icon name="plus" />Add {text ? 'text' : 'box'} shadow</button><button className={s.outlineButton} aria-pressed={!list.length} onClick={() => commit([])}>None</button></div>
    {!list.length && <p className={h.empty}>No {text ? 'text' : 'box'} shadow. Add one or choose a preset.</p>}
    <details className={`${s.presetDisclosure} ${h.disclosure}`}><summary><Icon name="layers" />{name} shadow presets<small>{presets.length}</small><Icon name="chevron" /></summary><div className={h.browser} role="region" aria-label={`${name} shadow preset browser`} tabIndex={0}>{[...new Set(presets.map(preset => preset.group))].map(group => <div key={group} className={h.presetGroup}>{!text && <h4>{group}</h4>}<div className={h.presetGrid}>{presets.filter(preset => preset.group === group).map(preset => <button key={preset.name} aria-label={`${name} shadow preset ${preset.name}`} title={preset.name} aria-pressed={value === preset.css} onClick={() => { editor!.apply(design!.targetId, property, preset.css); setSelected(0); }}><span className={h.preview} aria-hidden="true">{text ? <b className={h.textSample} style={{ textShadow: preset.css }}>Aa</b> : <span className={h.boxSample} style={{ boxShadow: preset.css }} />}</span><small>{preset.name}</small></button>)}</div></div>)}</div></details>
    {!!list.length && <div className={`${s.backgroundLayers} ${h.layers}`}><div className={h.layerCount}>{list.length} {list.length === 1 ? 'shadow' : 'shadows'}<span>{list.filter(item => !originalShadow(item)).length} visible</span></div>{list.map((item, i) => <div className={`${s.layer} ${h.layer} ${i === index ? s.chosenLayer : ''}`} data-hidden={!!originalShadow(item)} key={i}><button className={s.layerSelect} aria-label={`Select ${name.toLowerCase()} shadow ${i + 1}`} aria-pressed={i === index} onClick={() => setSelected(i)}><span className={h.layerName}>Shadow {i + 1}<small>{originalShadow(item) ? 'Hidden' : 'Visible'}</small></span></button><IconButton icon="up" label={`Move ${name.toLowerCase()} shadow ${i + 1} up`} disabled={i === 0} onClick={() => move(i, i - 1)} /><IconButton icon="down" label={`Move ${name.toLowerCase()} shadow ${i + 1} down`} disabled={i === list.length - 1} onClick={() => move(i, i + 1)} /><IconButton icon={originalShadow(item) ? 'eyeOff' : 'eye'} label={`${originalShadow(item) ? 'Show' : 'Hide'} ${name.toLowerCase()} shadow ${i + 1}`} onClick={() => commit(list.map((other, at) => at === i ? originalShadow(item) ?? hiddenShadow(item) : other))} /><IconButton icon="delete" label={`Remove ${name.toLowerCase()} shadow ${i + 1}`} onClick={() => commit(list.filter((_, at) => at !== i))} /></div>)}</div>}
    {shadow && <div className={`${s.richDetails} ${h.editor}`} data-shadow-editor={name}><div className={h.editorHeading}><span>Selected shadow {index + 1}</span><small>{original ? 'Hidden' : 'Visible'}</small></div><div className={`${h.values} ${text ? h.textValues : ''}`}>{(['x', 'y', 'blur', ...(!text ? ['spread'] : [])] as const).map(field => <label className={s.fieldLabel} key={field}><span>{field === 'x' || field === 'y' ? field.toUpperCase() : field[0].toUpperCase() + field.slice(1)}</span><NumericScrubber label={`${name} shadow ${field}`} value={shadow[field as 'x']} defaultUnit="px" min={field === 'blur' ? 0 : -Infinity} onChange={(next, gesture) => update({ [field]: next }, gesture)} /></label>)}</div><div className={h.color}><span>Color</span><ColorControl label={`${name} shadow color`} value={shadow.color} onChange={(color, gesture) => update({ color }, gesture)} /></div>{!text && <label className={`${s.inline} ${h.inset}`}><input aria-label="Inset shadow" type="checkbox" checked={shadow.inset} onChange={event => update({ inset: event.target.checked })} />Inset</label>}</div>}
    {!shadow && list.length > 0 && <p className={s.fixtureNote}>This shadow syntax is preserved. Choose a preset to replace it, or add a supported shadow.</p>}
  </Section>;
}
export function RichFilters() { const { editor, design } = useEditing(); return <Section name="Filters"><div className={s.filters}>{filterSpecs.map(spec => <FilterSlider key={spec.name} {...spec} />)}</div><button className={s.outlineButton} onClick={() => editor!.apply(design!.targetId, 'filter', 'none')}><Icon name="reset" />Reset filters</button></Section>; }
function FilterSlider({ name, label, initial, unit, max }: typeof filterSpecs[number]) {
  const { editor, design, context } = useEditing();
  const current = readFilter(design!.values.filter.presented, name, initial, unit);
  const [value, setValue] = useState(current.value); const pending = useRef<number | null>(null), frame = useRef(0), gesture = useRef('');
  const targetId = design!.targetId, scope = contextKey(context);
  useEffect(() => setValue(current.value), [current.value, targetId, scope]);
  useEffect(() => () => { cancelAnimationFrame(frame.current); pending.current = null; }, [targetId, scope]);
  const apply = (amount: number, id?: string) => { const snapshot = editor!.getSnapshot(); if (snapshot.design?.targetId !== targetId || contextKey(snapshot.context) !== scope || !Number.isFinite(amount)) return false; return editor!.applyBatch(targetId, { filter: updateFilter(snapshot.design.values.filter.presented, name, amount, unit) }, id, scope); };
  const flush = () => { cancelAnimationFrame(frame.current); frame.current = 0; const amount = pending.current; pending.current = null; if (amount !== null) { setValue(amount); apply(amount, gesture.current); } };
  return <div className={s.proFilter}><div><span>{label}</span><NumericScrubber label={`${label} value`} value={`${value}${unit}`} units={[]} min={name === 'hue-rotate' ? -360 : 0} disabled={!current.editable} onChange={(next, id) => { if (!new RegExp(`^-?\\d*\\.?\\d+${unit}$`).test(next)) return false; return apply(parseFloat(next), id); }} /></div><input aria-label={label} title={current.editable ? `${label} filter` : 'Existing complex or repeated function preserved; slider unavailable.'} type="range" disabled={!current.editable} min={name === 'hue-rotate' ? Math.min(0, current.value) : 0} max={Math.max(max, current.value)} step={name === 'blur' ? 0.1 : 1} value={value} style={{ background: `linear-gradient(to right, var(--accent) ${value / Math.max(max, current.value) * 100}%, var(--control-border) ${value / Math.max(max, current.value) * 100}%)` }} onFocus={() => { gesture.current = crypto.randomUUID(); }} onPointerDown={() => { gesture.current = crypto.randomUUID(); }} onChange={event => { const next = Number(event.target.value); pending.current = next; if (!frame.current) frame.current = requestAnimationFrame(flush); }} onPointerUp={flush} onBlur={flush} /></div>;
}
