import { useState } from 'react';
import { useUI } from '../../state/ui';
import { Icon, IconButton } from '../shared/Icon';
import { Popover } from '../popovers/Popover';
import s from '../ui.module.css';
export function BottomDock() {
  const open = useUI(state => state.inspectorOpen);
  const surface = useUI(state => state.surface);
  const [paused, setPaused] = useState(false);
  return <nav className={s.dock} aria-label="CSSForge tools"><div className={s.dockCircle}><IconButton icon={paused ? 'play' : 'pause'} label={paused ? 'Resume fixture preview' : 'Pause fixture preview'} active={paused} onClick={() => { setPaused(!paused); useUI.getState().setInspector(paused); }} /></div><div className={s.dockCircle}><IconButton icon="changes" label="Open Changes" active={surface === 'changes'} onClick={() => useUI.getState().setSurface('changes')} /><span className={s.dockBadge}>5</span></div><div className={s.dockCapsule}><IconButton icon="layers" label="Open Navigator" active={surface === 'navigator'} onClick={() => useUI.getState().setSurface('navigator')} /><Popover id="Background tools" label={<Icon name="image" />} iconOnly><div className={s.menuCaption}>Background tools</div><p className={s.menuNote}>Layer controls and presets are available in the Design preview.</p><button className={s.menuOption} onClick={() => { useUI.getState().setTask('Design'); useUI.getState().setInspector(true); }}>Open Design<Icon name="back" /></button></Popover><Popover id="Measurement tools" label={<Icon name="ruler" />} iconOnly><div className={s.menuCaption}>Fixture geometry</div><p className={s.menuNote}>993 × 585.88 px<br />Padding: 32 px · Margin: 0 px</p></Popover><Popover id="Color tools" label={<Icon name="palette" />} iconOnly><div className={s.menuCaption}>Fixture palette</div><div className={s.palettePreview}>{['#24262c', '#ffffff', '#98deb7', '#c1a2ed'].map(color => <span key={color} style={{ background: color }} title={color} />)}</div></Popover><Popover id="Eyedropper information" label={<Icon name="pipette" />} iconOnly><div className={s.menuCaption}>Color sampling</div><p className={s.menuNote}>The page eyedropper will be connected in a later phase.</p></Popover><Popover id="More tools" label={<Icon name="more" />} iconOnly><div className={s.menuCaption}>CSSForge · Visual foundation</div><button className={s.menuOption} onClick={() => useUI.getState().setSurface('changes')}>Review fixture changes<Icon name="changes" /></button><button className={s.menuOption} onClick={() => useUI.getState().setSurface('navigator')}>Open Navigator<Icon name="layers" /></button></Popover></div><div className={s.dockCircle}><IconButton icon="screen" label={open ? 'Hide inspector panel' : 'Show inspector panel'} active={open} onClick={() => useUI.getState().setInspector(!open)} /></div><div className={s.dockCircle}><IconButton icon="power" label={open ? 'Hide fixture UI panels' : 'Show fixture UI panels'} onClick={() => { useUI.getState().setInspector(!open); useUI.getState().setSurface(null); }} /></div></nav>;
}
